version: '2'
services:
    rally-app:
        image: rally
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://rally-mariadb:3306/rally
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rally-mariadb:
        extends:
            file: mariadb.yml
            service: rally-mariadb
